package handler

import "testing"

func TestIsAutoGeneratedQuery(t *testing.T) {
	tests := []struct {
		name     string
		query    string
		expected bool
	}{
		// Should be filtered (auto-generated)
		{"English predict", "Based on the conversation above, write the user's most likely next message.", true},
		{"English most likely next", "What is the user's most likely next message?", true},
		{"Chinese predict 1", "根据以上对话，写出用户最可能发送的下一条消息。", true},
		{"Chinese predict 2", "根据对话上下文，预测用户的下一条消息。", true},
		{"Chinese predict 3", "写出用户最可能发送的消息", true},

		// Should NOT be filtered (legitimate user messages)
		{"Chinese answer", "用中文回答", false},
		{"Three.js request", "用 Three.js 写一个滚珠迷宫", false},
		{"Simple question", "1+1等于几", false},
		{"Code request", "帮我写一个 Python 脚本", false},
		{"English code", "Write a Python script to parse JSON", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := isAutoGeneratedQuery(tt.query)
			if result != tt.expected {
				t.Errorf("isAutoGeneratedQuery(%q) = %v, want %v", tt.query, result, tt.expected)
			}
		})
	}
}
