package promptcompat

import "testing"

func TestIsAutoGeneratedMessage(t *testing.T) {
	tests := []struct {
		name     string
		query    string
		expected bool
	}{
		{"English predict", "Based on the conversation above, write the user's most likely next message.", true},
		{"English most likely", "What is the user's most likely next message?", true},
		{"Chinese predict 1", "根据以上对话，写出用户最可能发送的下一条消息。", true},
		{"Chinese predict 2", "根据对话上下文，预测用户的下一条消息。", true},
		{"Chinese predict 3", "写出用户最可能发送的消息", true},
		{"Legitimate Chinese", "用中文回答", false},
		{"Legitimate code", "用 Three.js 写一个滚珠迷宫", false},
		{"Legitimate English", "Write a Python script", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := isAutoGeneratedMessage(tt.query)
			if result != tt.expected {
				t.Errorf("isAutoGeneratedMessage(%q) = %v, want %v", tt.query, result, tt.expected)
			}
		})
	}
}
